name: cart_repository
description: The repo that manages cart data
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # firebase_auth: ^4.16.0
  cloud_firestore: ^6.0.0
  # equatable: ^2.0.7
  # firebase_storage: ^13.0.5
  # rxdart: ^0.27.7
  # path: ^1.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true